const activities = {
  "Housing Consultation": [
    "Assisting the person to access documentation required for Housing Stabilization Services eligibility",
    "Developing a Housing Focused Person-Centered Plan based on assessment outcomes",
    "Supporting the person in identifying their strengths, needs and wants in housing including cultural requirements and/or preferences",
    "Supporting the person to make an informed choice in their housing transition or sustaining provider",
    "Offering resource information for services that support non-housing related goals as identified in the person-centered planning process",
    "Coordinating with other service providers currently working with the person",
    "Helping the person understand their rights to privacy and appeal information",
    "Annually updating the person-centered plan as it relates to housing",
  ],
  "Housing Transition": [
    "Developing a housing transition plan",
    "Supporting the person in applying for benefits to afford their housing",
    "Assisting the person with the housing search and application process",
    "Assisting the person with tenant screening and housing assessments",
    "Providing transportation with the person receiving services present and discussing housing related issues",
    "Helping the person understand and develop a budget",
    "Helping the person understand and negotiate a lease",
    "Helping the person meet and build a relationship with a prospective landlord",
    "Promoting/supporting cultural practice needs and understandings with prospective landlords, property managers",
    "Helping the person find funding for deposits",
    "Helping the person organize their move",
    "Researching possible housing options for the person",
    "Contacting possible housing options for the person",
    "Identifying resources to pay for deposits or home goods",
    "Identifying resources to cover moving expenses",
    "Completing housing applications on behalf of the service recipient",
    "Working to expunge records or access reasonable accommodations",
    "Identifying services and benefits that will support the person with housing instability",
    "Ensuring the new living arrangement is safe for the person and ready for move-in",
    "Arranging for adaptive house related accommodations required by the person",
    "Arranging for assistive technology required by the person",
  ],
  "Housing Sustaining": [
    "Developing, updating and modifying the housing support and crisis/safety plan on a regular basis",
    "Preventing and early identification of behaviors that may jeopardize continued housing",
    "Educating and training on roles, rights, and responsibilities of the tenant and property manager",
    "Transportation with the person receiving services present and discussing housing related issues",
    "Promoting/supporting cultural practice needs and understandings with landlords, property managers and neighbors",
    "Coaching to develop and maintain key relationships with property managers and neighbors",
    "Advocating with community resources to prevent eviction when housing is at risk and maintain person's safety",
    "Assistance with the housing recertification processes",
    "Continued training on being a good tenant, lease compliance, and household management",
    "Supporting the person to apply for benefits to retain housing",
    "Supporting the person to understand and maintain/increase income and benefits to retain housing",
    "Supporting the building of natural housing supports and resources in the community including building supports and resources related to a person's culture and identity",
    "Working with property manager or landlord to promote housing retention",
    "Arranging for assistive technology",
    "Arranging for adaptive house related accommodations",
  ],
  "Moving Expenses": [
    "Applications, security deposits, and the cost of securing documentation that is required to obtain a lease on an apartment or home",
    "Essential household furnishings required to occupy a person's home, including furniture, window coverings, food preparation items, and bed and bath linens",
    "One-time set-up fees or deposits for utility or service access, including telephone, electricity, heating, and water",
    "Necessary home accessibility adaptations such as grab bars in the bathroom, doorbells that blink, sound alerts, alarms on doors, entryway ramps, etc.",
    "Services necessary for the individual's health and safety, such as pest eradication and one-time cleaning before occupancy",
  ],
};
export default activities;
